cameras:
  test_video:
    enabled: true
    best_image_timeout: 10
    source:
      path: '/home/nguyentt/Projects/edge/tests/src/video.mp4'
      ffmpeg:
        retry_interval: 5.0
        input_args: mp4_generic
        hwaccel_args: va_api
    detect:
      height: 320
      width: 320
      fps: 10
