cameras:
  test_video:
    enabled: true
    best_image_timeout: 10
    source:
      path: 'rtsp://localhost:8554/debug_stream'
      ffmpeg:
        retry_interval: 5.0
        input_args: rtsp_generic
        hwaccel_args: va_api
    detect:
      height: 320
      width: 320
      fps: 10
